### ISSUE TITLE
Ragged tensors related issues during conversion to ONNX format.

### ISSUE THREAD

**Issue by LoicDagnas** [onnx/tensorflow-onnx#1651] opened 2021-08-06 15:41 UTC
**Describe the bug**
Converting two different custom TensorFlow models from saved model format to ONNX format, I get some issues related to ragged tensor. Indeed, 
* my first model uses `tf.RaggedTensor.from_tensor` and `tf.RaggedTensor.from_row_splits`, and trying to convert it gives the following error:
```
ERROR - Failed to convert node 'All' (fct=<bound method AllAny.version_6 of <class 'tf2onnx.onnx_opset.reduction.AllAny'>>)
'OP=All\nName=All\nInputs:\n\tall_raggedfromtensor_equal:0=Placeholder, [-1, 167], 9\n\tall_raggedfromtensor_range:0=Placeholder, [0], 6\nOutpus:\n\tAll:0=None, 9'
[...]
ValueError: get tensor value: 'all_raggedfromtensor_range' must be Const
```
* my second model uses `tf.RaggedTensor.from_value_rowids` and `to_tensor` on a ragged tensor and its conversion gives the following error:
```
ValueError: make_sure failure: Only ROW_SPLITS partition type is supported for RaggedTensorToTensor. types: [b'FIRST_DIM_SIZE', b'VALUE_ROWIDS']
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10.0.19042
- Tensorflow Version: 2.5.0
- Python version: 3.7.6

**To Reproduce**
Get one of the model [here](https://drive.google.com/drive/folders/1TWGYg7LpoqL8ImQcxS6gPaOQ6Y5jZmBN?usp=sharing) and simply run the following command:
```
python -m tf2onnx.convert --saved_model path/to/pb --output path/to/onnx --tag serve --signature_def serve --opset 14
```

My main hypothesis is that the operations listed above are not supported yet (except `from_row_splits` maybe), if it is the case, is it planned to support these ops in a near future?

Thanks

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-08 05:03
For the second model, I can confirm that it is using values that we don't yet support for RaggedTensorToTensor, but I should be able to implement them by the end of next week.

For the first model, the conversion failure is caused by a non-constant input to the All/Any axis.  I'll have to take a closer look to see what I can do about that.  I think I can find a fix.

**Comment by LoicDagnas** [comment] 2021-08-09 07:50
@TomWildenhain-Microsoft , thank you !

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-10 00:14
#1657

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-11 18:01
Ragged tensors: #1664

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-13 01:12
@LoicDagnas both fixes have merged.  Can you please try the models again with the latest tf2onnx from master?

**Comment by LoicDagnas** [comment] 2021-08-13 07:41
Hello @TomWildenhain-Microsoft, yes, the conversion seems to work perfectly! 

I'am going to try the inference, I'll open a new issue if I have new problems.

Thanks again for providing two solutions so quickly!

**Closed** 2021-08-13 07:42 UTC
