### ISSUE TITLE
CuDNNGRU giving wrong output in Onnx

### ISSUE THREAD

**Issue by rvnth** [onnx/tensorflow-onnx#939] opened 2020-05-28 14:46 UTC
**Describe the bug**
I have a keras model that uses CuDNNGRU which I tried to convert to Onnx. I saved the keras model as a tensorflow frozen graph (.pb) and used tf2onnx to convert it. The inference output of onnx model is different compared to keras/tensorflow

**Urgency**
I want to publish this model to production via TRT. Since Onnx is the only way for converting GRUs from keras to TRT as informed by Nvidia contacts, I am blocked by this.

**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- Tensorflow Version: 1.15.2
- Python version: 3.6.9

**To Reproduce**
A sample model code I used to test this:
```
import tensorflow as tf
from tensorflow.python.framework import graph_util, graph_io
from keras.layers import Input, CuDNNGRU
from keras.models import Model
from keras import backend as K
from keras.backend.tensorflow_backend import set_session
import numpy as np

inp = Input(shape=(1, 5), name='input')
s = Input(shape=(8,), name='state')
out = CuDNNGRU(8, return_sequences=True, name='gru') (inp, initial_state=s)
m = Model(inputs=[inp, s], outputs=out, name='simplenet')
m.compile(loss='mse', optimizer='adam')

x = np.random.rand(100, 1, 5)
s = np.zeros((100, 8))
y = np.random.rand(100, 1, 8)
m.fit([x,s], y, epochs=5, batch_size=4)
m.save('simplenet.h5')

output_op = tf.identity(m.outputs[0], name='out_node')
sess = K.get_session()
constant_graph = graph_util.convert_variables_to_constants(sess, sess.graph.as_graph_def(),
                                                           ['out_node'])
graph_io.write_graph(constant_graph, "", 'simplenet.pb', as_text=False)
```
Converted the generated pb file to onnx using:
`python -m tf2onnx.convert --input simplenet.pb --output simplenet.onnx --inputs input:0,state:0 --outputs out_node:0 --opset 11`

Code used to compare the outputs:
```
import numpy as np
x1 = np.random.rand(1,1,5)
x2 = np.random.rand(1,8)

import onnx
import onnxruntime
s = onnxruntime.InferenceSession('simplenet.onnx')
out_1 = s.run(None, {'input:0': x1, 'state:0': x2})

from keras.models import load_model
m = load_model('simplenet.h5')
out_2 = m.predict([x1, x2])
```
out_1 and out_2 are different.

**Expected behavior**
Outputs of Keras and Onnx should match

**Comment by rvnth** [comment] 2020-06-12 19:15
Devs can you confirm if this is a know issue and if there is any plan on fixing this ?

**Comment by jignparm** [comment] 2020-06-12 20:50
@rvnth, thanks for the issue and the detailed instructions to reproduce. The output from the onnx model should not be different from TF, since the conversion was successful. 

It's on the radar to be fixed.

 In the meanwhile, can try TF 2.1 or 2.2 to see problem persists in later versions? We've noticed some conversion errors for TF 1.15 models that don't occur when using  TF  2.x models.

**Comment by jignparm** [comment] 2020-06-26 00:07
@rvnth , I seem to be hitting this error, using TF 2.2 and Keras 2.4.3. Were you able to run this on the more recent versions of TF, or it only runs on TF1.15?


```
$ pip show keras
Name: Keras
Version: 2.4.3

$ pip show tensorflow
Name: tensorflow
Version: 2.2.0

$ python createmodel.py
Traceback (most recent call last):
  File "createmodel.py", line 4, in <module>
    from keras.layers import Input, CuDNNGRU
ImportError: cannot import name 'CuDNNGRU' from 'keras.layers' (D:\anaconda373\lib\site-packages\keras\layers\__init__.py)
```

**Comment by guschmue** [comment] 2021-04-07 22:46
I close this one because in tf-2.x it does not exist anymore.

**Closed by guschmue** 2021-04-07 22:46 UTC
