### ISSUE TITLE
error in inferencing onnx model of bvlc_googlenet

### ISSUE THREAD

**Issue by Ason93** [onnx/tensorflow-onnx#531] opened 2019-05-21 02:23 UTC
1) convert pb model of bvlc_googlenet  to onnx:
python3 -m tf2onnx.convert --input ~/code/models/bvlc_googlenet/bvlc_googlenet.pb --inputs Placeholder:0[1,224,224,3] --outputs prob:0 --output ~/code/models/bvlc_googlenet/bvlc_googlenet.onnx --verbose

2)    create an inference session to begin working with onnx model and run the inference session with my selected outputs and inputs to get the predicted value
    m = rt.InferenceSession(model_path)
    input_name = m.get_inputs()[0].name
    X = np.random.random((1, 224, 224, 3)).astype(np.float32)
    results = m.run(outputs, {input_name: X})

But while inferencing onnx, there is an error:

Traceback (most recent call last):
  File "pb2onnx.py", line 180, in <module>
    onnx_results = run_onnxruntime(name=None, model_proto=None, model_path=output)
  File "pb2onnx.py", line 22, in run_onnxruntime
    m = rt.InferenceSession(model_path)
  File "/home/cxjin/.local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 29, in __init__
    self._sess.load_model(path_or_bytes)
RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cpu/nn/lrn.h:22 onnxruntime::LRN<T>::LRN(const onnxruntime::OpKernelInfo&) [with T = float] size_ % 2 == 1 was false.

**Comment by zhijxu-MS** [comment] 2019-06-13 09:08
could you please share with me the link to download the model pb?

**Comment by Ason93** [comment] 2019-06-14 03:34
Hello! This is my test model, bvlc_googlenet.pb. Link:https://pan.baidu.com/s/1SDb0QJViZEoy6fTnlNXsFQ, password: 7nu5









At 2019-06-13 17:08:22, "zhijxu-MS" <notifications@github.com> wrote:


could you please share with me the link to download the model pb?

**Comment by lei-Qiao** [comment] 2019-06-17 08:30
Hello, the problem caused by lrn during inference session is sovled by PR #602 . However, a new problem occurs during inference session:

RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : Load model from bvlc_googlenet.onnx failed:Node:prob Output:prob:0 [ShapeInferenceError] Can't merge shape info. Both source and target dimension have values but they differ. Source=0 Target=1 Dimension=0

And I am still working on it.

**Comment by lei-Qiao** [comment] 2019-06-20 03:33
Hello, the problem is solved. You can convert pb model of bvlc_googlenet to onnx and run the inference session now.

**Comment by lucienwang1009** [comment] 2019-07-10 03:41
Hi @Ason93 this issue seems to have been fixed. I will close it.

**Closed by lucienwang1009** 2019-07-10 03:41 UTC
Labels: pending on user response
