### ISSUE TITLE
Please fix onnx-weekly CI failure to enhance tf2onnx and ONNX robustness

### ISSUE THREAD

**Issue by jcwchen** [onnx/tensorflow-onnx#1860] opened 2022-02-19 22:50 UTC
[onnx-weekly CI ](https://dev.azure.com/tensorflow-onnx/tensorflow-onnx/_build?definitionId=30&_a=summary) fails for quite a while. The last successful run is this [one](https://dev.azure.com/tensorflow-onnx/tensorflow-onnx/_build/results?buildId=16099&view=results) on 11/15/2021. Then it stared to fail since 11/23/2021. There is only one [PR ](https://github.com/onnx/onnx/pull/3557) which might cause this failure at that period (11/15~11/24), but IMO it should not be the root cause because it is a new proposed ONNX op and there shouldn't be any test related to it. So I thought the failure was probably caused by other reason, but until today the CI failure has not been fixed yet. 

I suppose making this CI running can benefit both tf2onnx and ONNX -- the latest tf2onnx can weekly verify its new things with the latest ONNX, and vice versa. For instance, during the recent  ONNX 1.11 verification with tf2onnx, we found an ONNX bug and a tf2onnx test bug. With this weekly-CI, such potential bugs can be detected in early stage and be fixed early.

Since @fatcat-z has just verified ONNX 1.11 with tf2onnx, I think right now should be a good time to fix it, because there shouldn't be any failure caused by ONNX. Still, if there is anything related to ONNX which needs to be fixed, I am willing to help. Thank you for the assistance and support!

**Comment by jcwchen** [comment] 2022-03-01 01:39
> It seems it didn't run at all in December and January. Since February it's been running regularly.

Actually I did receive emails about onnx-weekly CI failures in December and January. Don't know why they were somehow deleted and now it cannot be checked.

**Comment by fatcat-z** [comment] 2022-03-08 04:22
This root cause of this issue relative to onnx, an issue https://github.com/onnx/onnx/issues/4053 was opened to track this.

**Comment by jcwchen** [comment] 2022-03-15 15:53
Thank you @fatcat-z so much for the fix. It seems that the onnx-weekly CIs has all succeeded. If yes, I can close this issue.

**Comment by fatcat-z** [comment] 2022-03-16 03:06
> Thank you @fatcat-z so much for the fix. It seems that the onnx-weekly CIs has all succeeded. If yes, I can close this issue.

Yes, it succeeds now. I will close this one and feel free to open a new one if it failed again.

**Closed by fatcat-z** 2022-03-16 03:06 UTC
