### ISSUE TITLE
Incorrect results for models with dynamic input shape.

### ISSUE THREAD

**Issue by tgey** [onnx/tensorflow-onnx#1112] opened 2020-09-23 13:04 UTC
**Describe the bug**
Tensorflow models with dynamic shape input converted to Onnx models return different results. The output shape of the Onnx model is correct but the values returned are different to those returned by the Tensorflow model. This difference only occurs if the shape is not defined.

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Tensorflow Version: 2.3.0
- Python version: 3.8.3

**To Reproduce**
Init a Tensorflow model with a dynamic input shape (i.e tf.keras.Input(shape=[None, None, 3])
Convert tf model into onnx model using tf2onnx (without any shape_override)
Load onnxruntime inference session using the new onnx model
Compare output mean/std from both Tensorflow and Onnx models.

**Expected behavior**
Output mean/std should be identical

**Screenshots**
A basic model with dynamic input shape (None, None, 3):
![model](https://user-images.githubusercontent.com/21363799/94015798-9fc6d900-fdad-11ea-9a61-da5b8372c7e7.png)

How I tested both models:
![onnx_run](https://user-images.githubusercontent.com/21363799/94016037-eae0ec00-fdad-11ea-8f9e-bd221de18189.png)

Results:
![output_onnx](https://user-images.githubusercontent.com/21363799/94015632-6d1ce080-fdad-11ea-892c-a059c60e50fe.png)

**Additional context**
Results are identical if the input shape is specified and static when converting from Tensorflow to Onnx using shape_override argument (i.e shape_override={'input_name:0: [1, 256, 256, 3]}).

**Comment by TomWildenhain-Microsoft** [comment] 2020-09-23 17:52
Thanks for the bug report.  Can you please provide your code for ConvLayer to make this easier to reproduce?  Thanks!

**Comment by TomWildenhain-Microsoft** [comment] 2020-09-23 18:08
Those numbers are still very close and may be within the margin of error.

**Comment by guschmue** [comment] 2020-09-24 03:53
I tried this myself with the random input range np.random.uniform(-1. - 1.)
```
tf mean/std =  -0.0006045878 0.115525395
onnx mean/std =  -0.0006045875 0.11552541
```
If I do a 
```
np.testing.assert_allclose(tf_res + 10., onnx_res + 10., rtol=1e-8)
```
I get:
```
Exception has occurred: AssertionError
Not equal to tolerance rtol=1e-08, atol=0
Mismatched elements: 3219 / 57600 (5.59%)
Max absolute difference: 9.536743e-07
Max relative difference: 1.0024399e-07
```
kind of saying the relative error per element is 1.0024399e-07 which is in the range we'd expect.

The onnx graph itself looks correct.

Your diff looks a little more. What range did you use for random ?
The model has the shape [1,None,None,3] and passed the shapes [1,150,150,3] and [1,224,224,3] - similar results.
Shape override should not change the result I belief.

**Comment by tgey** [comment] 2020-09-24 10:06
@TomWildenhain-Microsoft Here is the ConvLayer class:
![convLayer](https://user-images.githubusercontent.com/21363799/94130492-0b1bb400-fe5d-11ea-80dc-217999abbea4.png)

I agree the difference is very small for this model, but it represents only 3 convolutions. On a larger model like Yolact, the difference is very large and the converted model is no longer consistent with the original tensorflow model.

@guschmue For my example, I used a [0, 1] range.
![create_random](https://user-images.githubusercontent.com/21363799/94130934-9ac16280-fe5d-11ea-8095-22c866940617.png)

**Comment by guschmue** [comment] 2020-09-25 02:32
I tried with your values and my conv_layer is the same like yours:
```
tf mean/std       =  0.020584757 0.030996958
onnx mean/std  =  0.02058476 0.030996963

Mismatched elements: 2014 / 200704 (1%)
Max absolute difference: 9.536743e-07
Max relative difference: 9.5367405e-08
```
Pretty ok I think.

Some some questions: you are running on cpu and gpu. if cpu are you using avx2 or better (I know errors are slightly higher with avx2) ?
What version of onnxruntime do you use?

**Comment by guschmue** [comment] 2020-09-25 23:11
one thing my app is doing different - I run the keras inference before converting to onnx what might move the batchnorm out of training mode. I convert it in memory directly from the keras model using this function:
https://gist.github.com/guschmue/fdd66ec852c3d179a97bc08b3331d640

**Comment by tgey** [comment] 2020-09-28 07:52
We are using GPU only to run our model with onnxruntime-gpu==1.4.0.

for np.testing.assert_allclose(np.mean(tf_output) + 10., np.mean(onnx_output) + 10., rtol=1e-8), with your to_onnx method, we got:
![Screenshot from 2020-09-28 09-49-01](https://user-images.githubusercontent.com/21363799/94404935-0febab00-0170-11eb-99ed-2f6241960901.png)

Here is my full test script: https://gist.github.com/tgey/7e2dfd5ede22494c09d58a9028037832

**Comment by guschmue** [comment] 2020-09-28 15:05
yeah, this is worse than mine. I used cpu - let me try gpu.

**Comment by guschmue** [comment] 2020-09-28 20:42
with gpu I get:
```
tf mean/std =       0.020584758 0.030996958
onnx mean/std =  0.020435045 0.03079974

Not equal to tolerance rtol=1e-08, atol=0
Mismatched elements: 124753 / 200704 (62.2%)
Max absolute difference: 0.1477766
Max relative difference: 0.01477766
```
Ok, that is not so good.
It is similar when I keep tensorflow on cpu and only run onnxruntime on gpu.

Seems to be the onnxruntime cuda implementation.

I'd close this issue, open one against onnxruntime here: https://github.com/microsoft/onnxruntime and mention this issue in the new issue.

**Comment by tgey** [comment] 2020-09-29 07:14
Thank you for testing on both CPU and GPU and to have discovered an investigation lead.

I used CUDA 10.1 with a Nvidia RTX 2080.

Sincerely,

**Comment by guschmue** [comment] 2020-09-29 14:44
fyi @jywu-msft, @pranavsharma

**Comment by feiyuhuahuo** [comment] 2020-10-20 02:40
Hi, @tgey, @guschmue 
Do you know how to construct a model with dynamic input when there are other Ops in the model (like `tf.image.resize`)?
I try to use `tf.keras.Input(shape=[None, None, 3]` to construct a dynamic model but I get the following error:

`return tf.image.resize(input_layer, (input_layer.shape[1] * 2, input_layer.shape[2] * 2), method='nearest')
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'`

 `tf.image.resize` can't support None type input, how to solve this ?

**Comment by TomWildenhain-Microsoft** [comment] 2020-11-02 18:53
Try using a Shape op to measure the shape of the input and then pass that result to tf.image.resize.

**Comment by TomWildenhain-Microsoft** [comment] 2020-12-30 00:25
Let me know if you still need help with this issue.

**Comment by guschmue** [comment] 2021-02-25 15:31
assume fixed.

**Closed by guschmue** 2021-02-25 15:31 UTC
Labels: pending on user response
