### ISSUE TITLE
TF2 supported ?

### ISSUE THREAD

**Issue by tlepley-cadence** [onnx/tensorflow-onnx#809] opened 2020-02-21 16:03 UTC
I've updated the TF version to TF 2.1 and tried to convert a TF model to ONNX as usual (this model was created using the TF 1 compatibility API)

I got the following error:
``
 File "<...>//tensorflow-onnx/tf2onnx/tfonnx.py", line 20, in <module>
    from tensorflow.tools.graph_transforms import TransformGraph
``
Looking at some other issues, it seems that there is a TF2 branch for TF2ONNX.
Do you confirm ? And how stable is it ?

**Comment by guschmue** [comment] 2020-02-21 16:12
https://github.com/onnx/tensorflow-onnx/tree/gs/tf2 should be in decent state - we are working on merging it into master.
Running under tf-1.x all tests are passing.
Running under tf-2.x basic things should be fine. We switched to control flow to use the V2 control flow and there are a few issues left but we'll get a handle on it.

**Comment by guschmue** [comment] 2020-03-02 17:12
dupe of https://github.com/onnx/tensorflow-onnx/issues/691

**Closed by guschmue** 2020-03-02 17:12 UTC
