### ISSUE TITLE
list supported TF ops for each opset

### ISSUE THREAD

**Issue by nbcsm** [onnx/tensorflow-onnx#494] opened 2019-04-30 13:19 UTC
explicitly list which TF ops are supported in each opset so data scientists can avoid unsupported ones during model development.

**Comment by guschmue** [comment] 2019-04-30 14:46
dupe of https://github.com/onnx/tensorflow-onnx/issues/420 ?

**Comment by nbcsm** [comment] 2019-05-02 14:47
not quite sure whether #420 is for overall supported ops or for each opset.
@tjingrant, any update on #420 please?

**Comment by guschmue** [comment] 2019-06-21 16:33
fixed under #420

**Closed by guschmue** 2019-06-21 16:33 UTC
Labels: enhancement
