### ISSUE TITLE
 get different inference result with origin tensorflow model

### ISSUE THREAD

**Issue by PeterWang1986** [onnx/tensorflow-onnx#447] opened 2019-04-11 02:37 UTC
Hi all,
Recently I tried to convert my tensorflow model to onnx format, and take onnxruntime as backend, but I got the different inference result. I'm not sure is there anything I did wrong ?

You can find much more information from here:
1. tensorflow pb file: https://pan.baidu.com/s/1a5itDj6BQFcE9or1wWXY6w

2. convert command:
` python -m tf2onnx.convert --input=CSRNet.pb --inputs=Reshape:0[1,512,512,3] --outputs=backend/density_map/BiasAdd:0 --output=model_v1.onnx --opset=9`
I can see sys info:
>  **using tensorflow=1.13.1, onnx=1.4.1, opset=9, tfonnx=1.5.0/757ed9**

3. using onnxruntime as backend to call this onnx model, get 490.95. But when I use tensorflow to execute pb file, I can get 494.22.

4. I also tried onnx-tensorflow to convert my pb file, and then call it with onnxruntime, I can get the same result with tensorflow. Here is my convert script:
`import tensorflow as tf

from tensorflow.core.framework import graph_pb2

from onnx_tf.frontend import tensorflow_graph_to_onnx_model
from onnx_tf.pb_wrapper import TensorflowGraph

graph_def = graph_pb2.GraphDef()
with open("CSRNet.pb", "rb") as f:  # load tf graph def
    graph_def.ParseFromString(f.read())
    output = TensorflowGraph.get_output_node_names(graph_def) # get output node names

    # convert tf graph to onnx model
    # opset=0 will use latest onnx op version,
    # but currently onnx-tensorflow not support MaxPool under version 10
    model = tensorflow_graph_to_onnx_model(graph_def, output, opset=9)

with open("model_v2.onnx", 'wb') as f:
    f.write(model.SerializeToString())`

If you need much info, please tell me. Thanks for your help.

**Comment by nbcsm** [comment] 2019-04-11 03:14
thanks for reporting.
it would be helpful to share your onnx models (both onnx-tensorflow and tensorflow-onnx) as well.
we will take a look and get back to you later.

sorry but it probably take a while since we are busy with opset10 currently.
if you find the root cause before that, feel free to send a PR. :-)

**Comment by PeterWang1986** [comment] 2019-04-11 07:34
hi nbcsm,
here is the onnx models:
model_v1 for tensorflow-onnx: https://pan.baidu.com/s/1JY3T-E0P7Dj--1zlkOTiqw
model_v2 for onnx-tensorflow: https://pan.baidu.com/s/1S1fmxViT12dQkLx1os9eGA

BTW: the model_v1 is faster than model_v2 when using onnxruntime as backend (0.86s vs 4.4s)

**Comment by nbcsm** [comment] 2019-04-11 13:07
thanks for the detail information.

**Comment by PeterWang1986** [comment] 2019-04-12 07:55
Hi all,
Here are some findings from my side:
1. model_v1 and model_v2 have different `pads` on `vgg_16/conv1/conv1_1/Conv2D`
   model_v1 with pads [0, 0, 0, 0] (I think this is incorrect)
   model_v2 with pads [1, 1, 1, 1]
   (my pb model also with [1, 1, 1, 1], padding = `SAME`)

2. then i checked add_padding method in onnx_opset/nn.py, it will use output_shape & input_shape to calculate the pad value, but in this case, we cannot get output shape (ret -1)

3. so i tried to use tf2onnx.tfonnx.process_tf_graph method with `shape_override` parameter.
    e.g. shape_override = {'Reshape:0': [1, 512, 512, 3], 'vgg_16/conv1/conv1_1/Conv2D:0': [1, 512, 512, 64]}

4. then i can get the correct inference result. :)

Here I have another question:
I found there are many `Transpose` operation in the new onnx model, but if I use
      `python -m tf2onnx.convert`
theses operations will be removed, and also merged some BiasAdd operations.

So how can I do the same thing with tf2onnx.tfonnx.process_tf_graph() method.

Thanks for your help.

**Comment by guschmue** [comment] 2019-04-12 16:31
for the last question: the graph returned by process_tf_graph() is not optimized (we should add that to the doc). You can call 
```model_proto = GraphUtil.optimize_model_proto(model_proto)```
after process_tf_graph().

Very likely your point 2 above is correct. Going to look at it today.

**Comment by guschmue** [comment] 2019-04-12 17:58
I have a fix for the missing dim in output shape here:
https://github.com/onnx/tensorflow-onnx/compare/gs/fix-mobilenetv2?expand=1
with that mobilenetv2 which had the same issue work now.
onnxruntime still has some shape inference issue with your model after that ... looking at that.

**Comment by PeterWang1986** [comment] 2019-04-15 01:49
Hi all,
Thanks for your support.
Peng

**Comment by guschmue** [comment] 2019-04-16 15:39
for the issue that the converted CSRNet.pb doesn't run on onnxruntime:
it fails in the onnx shape inference, as far I can tell its because the output shape has more than 1 unknown dim, other than that I think the model should work.

The unknown dim in the output is because the unknown dims from the input placeholder propagates through the network and ends up in the output. When you override the shape in the tf2onnx command line that sets our internal shape (not the tensorflow one) but our internal shape inference doesn't handle all ops and when we fall back to tensorflows shape inference it would have the unknown dim from the the placeholder.

3 ways of fixing this:
1. we make our internal shape inference take care of it. Probably more work than we think.
2. when we override the input shape we re-write the tensorflow placeholder with the new shape
3. we change your code that wraps the converter to do 2 in your code

Let me see if 2 works.

**Comment by nbcsm** [comment] 2019-04-17 02:41
we have seen similar issue when dealing with other models.
https://github.com/Microsoft/onnxruntime/issues/829

onnxruntime throws onnx shape inference exception out, but if we add a try/catch to swallow the exception, model can run actually.

**Comment by PeterWang1986** [comment] 2019-04-18 08:03
Hi all,
My onnx model can work correctly now (take onnxruntime as backend).
Thank you very much for your support.

And I used bellow command to convert my model:
`
python -m tf2onnx.convert \
  --input=CSRNet.pb \
  --inputs=Reshape:0[1,512,512,3],vgg_16/conv1/conv1_1/Conv2D:0[1,512,512,64] \
  --outputs=backend/density_map/BiasAdd:0 \
  --inputs-as-nchw=Reshape:0 \
  --output=model_v1.onnx \
  --opset=9 \
  --verbose
`

**Comment by guschmue** [comment] 2019-04-19 02:55
perfect!

**Comment by nbcsm** [comment] 2019-04-26 14:57
close it.

**Closed by nbcsm** 2019-04-26 14:57 UTC
