### ISSUE TITLE
Range op causes the input tensor name cannot be find

### ISSUE THREAD

**Issue by jiafatom** [onnx/tensorflow-onnx#387] opened 2019-03-18 22:26 UTC
When I convert tf to onnx, I have a onnx runtime error:
RuntimeError: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from model_data/yolov3.onnx failed:Node:TFNodes_yolo_evaluation_layer_1_arange_4__1261_loop Nodes in a graph must be topologically sorted, however input 'TFNodes/yolo_evaluation_layer_1/arange_4/delta:0' of node: 
input: "prev" input: "TFNodes/yolo_evaluation_layer_1/arange_4/delta:0" output: "current" name: "add__1264" op_type: "Add"
 is not output of any previous nodes.

This is because I want to convert tf.arange, which is a Range op in tensorflow, and in tf2onnx, we use tensorflow-onnx/tf2onnx/function/range.py
Here we use a Loop op and there is a subgraph in it. 
The input is TFNodes_yolo_evaluation_layer_1_arange_4_delta_0
But when I dump the subgraph in the Loop op, I see the input for Add op is: 
TFNodes/yolo_evaluation_layer_1/arange_4/delta:0
Here we have '/' rather than '_' in the names. So it cannot find the correct input, and causing error. 

Could someone help with this? Thank you!

**Comment by nbcsm** [comment] 2019-03-20 03:39
synced with @jiafatom offline, the root cause is not in tf2onnx, close this issue.

**Closed by nbcsm** 2019-03-20 03:39 UTC
