### ISSUE TITLE
Please verify ONNX v1.10.0 Release Candidate

### ISSUE THREAD

**Issue by rajeevsrao** [onnx/tensorflow-onnx#1623] opened 2021-07-22 17:45 UTC
Hello ONNX partner,
We have published (to TestPyPI) a Release Candidate package for the upcoming ONNX v1.10.0 release. Please help validate it and let us know if you encounter any issues. Note that the tentative release date for ONNX v1.10.0 is July 31, 2021. Thank you for your assistance!

```
pip install numpy protobuf typing-extensions>=3.6.2.1
pip install -i https://test.pypi.org/simple/ onnx==1.9.101
```

* 07/26/2021: RC2 with `make_sequence_value_info` alias - [onnx 1.9.101](https://test.pypi.org/project/onnx/1.9.101/)
* 07/21/2021: RC1 for validation - [onnx 1.9.100](https://test.pypi.org/project/onnx/1.9.100/)

cc @guschmue @TomWildenhain-Microsoft

**Comment by TomWildenhain-Microsoft** [comment] 2021-07-22 21:46
@rajeevsrao some tests are failing due to the error:
`AttributeError: module 'onnx.helper' has no attribute 'make_sequence_value_info'`
Did you remove `onnx.helper.make_sequence_value_info`?

**Comment by rajeevsrao** [comment] 2021-07-22 22:45
@TomWildenhain-Microsoft for `TensorProto`, `make_sequence_value_info` is now renamed to `make_tensor_sequence_value_info` so please update your code accordingly. For the newly introduced `SparseTensorProto` we now have `make_sparse_tensor_value_info`. FYI: https://github.com/onnx/onnx/pull/3407/files

**Comment by TomWildenhain-Microsoft** [comment] 2021-07-22 22:55
I see.  To avoid breaking existing code, would it be possible to make `make_sequence_value_info` call `make_tensor_sequence_value_info` (and possibly display a deprecation message)?  I see that there are some redundant names already:

https://github.com/onnx/onnx/blob/a57bc99daa6ddeef2ad535f8f78d1847f57216f0/onnx/__init__.py#L220

**Comment by askhade** [comment] 2021-07-23 05:21
The intention was to clean up the existing apis and make them more intuitive... existing apis were error prone. Since sequence ops are not yet very popular we decided to deprecate this api in this release. 

How difficult is it to make this change in tensorflow-onnx converter? Is it a lot of effort?

**Comment by TomWildenhain-Microsoft** [comment] 2021-07-23 05:33
No it's not a big deal for the converter, though we'll need to case on the version and still use the old API for previous versions.  I have another script that will need to be updated.  Also not a big deal but the casing logic is ugly.  Just thought it might be cleaner to make an alias to it.

**Comment by guschmue** [comment] 2021-07-23 16:32
+1 for Tom. One does not change existing api's because you'd force all consumers to now look at the onnx version and depending on that version you need to call a different method. Considering that onnx is the onnx python module is called by a lot of applications we badly would want to avoid this!

**Comment by rajeevsrao** [comment] 2021-07-23 17:34
@guschmue agree that removing the API on short-notice is not advisable. We will post a change with the alias for maintaining backwards compatibility in this release. However this will be on the deprecation schedule (pending clarification from ONNX working groups) and likely going to be removed in a future release. Will post an update to the packages shortly. Thanks.

**Comment by guschmue** [comment] 2021-07-23 17:41
Cool. For longer term  - I think its never good to change api's and force everybody to update.
But the sig/community should decide.

**Comment by TomWildenhain-Microsoft** [comment] 2021-07-23 17:44
_Technically_ if you do change the API I think you need to increase the major version number (2.0.0 not 1.10.0) so PyPI versioning works properly.

**Comment by rajeevsrao** [comment] 2021-07-26 08:27
@TomWildenhain-Microsoft @guschmue RC2 with `make_sequence_value_info` alias is now posted - please help validate [v1.9.101](https://test.pypi.org/project/onnx/1.9.101/)

**Comment by TomWildenhain-Microsoft** [comment] 2021-07-26 20:26
All conversions are working now but I'm getting some test failures with the onnx checker in opset 8.  It seems like for old opsets, initializers for constants had to have a corresponding input entry, which the checker does not like for loop subgraphs.

On a converted model in opset 8 I get errors like:
`onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] Shape inference error(s): (op_type:Loop, node name: while_loop): [ShapeInferenceError] Graph has 7 inputs but 3 were provided`

Line of tf2onnx adding the inputs:
https://github.com/onnx/tensorflow-onnx/blob/93fe84456c0f87a87eaeb01d74df277db977cf08/tf2onnx/graph.py#L1148

I guess the real issue here is **optional inputs in subgraphs of Loop nodes should not cause an error if they do not have a corresponding input in the node**.

**Comment by TomWildenhain-Microsoft** [comment] 2021-07-26 20:28
Example model:
```python
from onnx import helper, numpy_helper, TensorProto
from onnx.helper import make_node, make_graph

import onnx
import numpy as np

model = helper.make_model(
    opset_imports=[helper.make_operatorsetid('', 8)],
    ir_version=4,
    producer_name='tf2onnx',
    producer_version='1.8.0',
    graph=make_graph(
        name='tf2onnx',
        inputs=[
            helper.make_tensor_value_info('input:0', TensorProto.INT32, shape=[1]),
            helper.make_tensor_value_info('while/maximum_iterations:0', TensorProto.INT64, shape=[]),
            helper.make_tensor_value_info('const_fold_opt__18', TensorProto.INT64, shape=[1]),
            helper.make_tensor_value_info('const_fold_opt__17', TensorProto.FLOAT, shape=[]),
            helper.make_tensor_value_info('Const:0', TensorProto.INT32, shape=[1]),
        ],
        outputs=[helper.make_tensor_value_info('output:0', TensorProto.INT32, shape=[1])],
        initializer=[
            numpy_helper.from_array(np.array(9223372036854775807, dtype=np.int64), name='while/maximum_iterations:0'),
            numpy_helper.from_array(np.array([-1], dtype=np.int64), name='const_fold_opt__18'),
            numpy_helper.from_array(np.array(10.0, dtype=np.float32), name='const_fold_opt__17'),
            numpy_helper.from_array(np.array([1], dtype=np.int32), name='Const:0'),
        ],
        doc_string='test',
        nodes=[
            make_node('Cast', inputs=['input:0'], outputs=['while_cond_158_while/Less__13:0'], name='while_cond_158_while/Less__13', domain='', to=TensorProto.FLOAT),
            make_node('Less', inputs=['while_cond_158_while/Less__13:0', 'const_fold_opt__17'], outputs=['while_cond_158_while/Less:0'], name='while_cond_158_while/Less', domain=''),
            make_node('Squeeze', inputs=['while_cond_158_while/Less:0'], outputs=['while_cond_158_while/Squeeze:0'], name='while_cond_158_while/Squeeze', domain=''),
            make_node(
                'Loop',
                inputs=['while/maximum_iterations:0', 'while_cond_158_while/Squeeze:0', 'input:0', 'Const:0'],
                outputs=['while_loop:0', 'while_loop:1'],
                name='while_loop',
                domain='',
                body=make_graph(
                    name='while_body_159',
                    inputs=[
                        helper.make_tensor_value_info('while_while_loop_counter:0', TensorProto.INT64, shape=[]),
                        helper.make_tensor_value_info('cond__15:0', TensorProto.BOOL, shape=[]),
                        helper.make_tensor_value_info('while_placeholder:0', TensorProto.INT32, shape=[1]),
                        helper.make_tensor_value_info('while_add_const_0:0', TensorProto.INT32, shape=[1]),
                        helper.make_tensor_value_info('const_fold_opt__19', TensorProto.FLOAT, shape=[]),
                    ],
                    outputs=[
                        helper.make_tensor_value_info('cond___while/Identity_graph_outputs_Identity__3:0', TensorProto.BOOL, shape=[]),
                        helper.make_tensor_value_info('while/Identity_2:0', TensorProto.INT32, shape=[1]),
                        helper.make_tensor_value_info('while_add_const_0:0', TensorProto.INT32, shape=[1]),
                    ],
                    initializer=[numpy_helper.from_array(np.array(10.0, dtype=np.float32), name='const_fold_opt__19')],
                    doc_string='graph for while_loop body',
                    nodes=[
                        make_node('Add', inputs=['while_placeholder:0', 'while_add_const_0:0'], outputs=['while/Identity_2:0'], name='while/Add'),
                        make_node('Cast', inputs=['while/Identity_2:0'], outputs=['cond___while/Less__13:0'], name='cond___while/Less__13', domain='', to=TensorProto.FLOAT),
                        make_node('Less', inputs=['cond___while/Less__13:0', 'const_fold_opt__19'], outputs=['cond___while/Less:0'], name='cond___while/Less', domain=''),
                        make_node('Squeeze', inputs=['cond___while/Less:0'], outputs=['cond___while/Identity_graph_outputs_Identity__3:0'], name='cond___while/Squeeze', domain=''),
                    ],
                ),
            ),
            make_node('Unsqueeze', inputs=['while_loop:0'], outputs=['Reshape/tensor:0'], name='Reshape/tensor', axes=[0]),
            make_node('Reshape', inputs=['Reshape/tensor:0', 'const_fold_opt__18'], outputs=['output:0'], name='Reshape'),
        ],
    ),
)

onnx.checker.check_model(model, full_check=True)
```

**Comment by gramalingam** [comment] 2021-07-26 21:30
Initial thoughts: I think this is an error and tf2onnx shouldn't do this. Do these models work with ORT? Specifically, the specification of the Loop op indicates that the subgraph inputs should be loop carried dependences. Constants/initializers are not expected to be in the subgraph inputs. (It is true that the requirements on initializers and inputs changed around the transition from IR version 3 to IR version 4.) From what I understand, these error messages were present in previous ONNX releases too, but it is only the strict-check option that has changed. But if these models work with ORT, may be there is a discrepancy between ORT and ONNX.

**Comment by TomWildenhain-Microsoft** [comment] 2021-07-26 22:06
Yes, the models work with ORT.  Note that the constant initializer inputs are always at the end of the input list so everything still lines up if you zip them with the loop carried dependencies.  For loops it is like if you had a python function that runs a loop node:

```python
def loop_runner(body, m, cond, *v_initial):
    """Runs a loop.  Body must take 2 + len(v_initial) inputs"""
    vs = v_initial
    i = 0
    while cond and i < m:
        cond, *vs = body(i, cond, *vs)
        i += 1
    return vs
```

And then gave it:
```python
def sum_n_body(i, cond, running_total, step=1):  # Has 3 or 4 inputs?  Only 3 expected.
    return True, running_total + i * step
result = loop_runner(sum_n_body, 100, True, 0)
```

It works but sum_n_body arguably has more inputs than expected...

I get the same error for If nodes.  Here I think the tf2onnx output is pretty clearly compliant, since the spec for the If op does not state that the graph should have no inputs.

`onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] Shape inference error(s): (op_type:If, node name: test_cond): [ShapeInferenceError] Graph has 1 inputs but 0 were provided`

I can easily disable the onnx checker for these tests in tf2onnx and this shouldn't block the onnx release, but it's a discrepancy to be aware of.  We already skip running the checker for a few tests anyway.

**Comment by guschmue** [comment] 2021-07-26 22:09
I think the problem might be that this is shared code that we use for the main onnx graph as well as the subgraph. For the main graph we have to add those constants to the input list, for the subgraph we should not I assume.

**Comment by TomWildenhain-Microsoft** [comment] 2021-07-26 22:11
Is there a reason we don't use the Constant op for constant values in IR <= 3 models?

**Comment by guschmue** [comment] 2021-07-26 22:12
For the main graph yes, not so sure about subgraphs (I fear the documentation will not say).

**Comment by TomWildenhain-Microsoft** [comment] 2021-07-26 22:44
This behavior definitely is not allowed in the new IR: https://github.com/onnx/onnx/commit/dc75285d4a1cff9618400164dfdb26c5a1bab70a#diff-abcfc88a55144836fff2a055d73bc894201789bda5c0de98594e931037b5ec21

> In nested subgraphs used as attribute values, users MUST NOT use the same name as both a subgraph initializer and subgraph input unless the corresponding op's specification explicitly allows it.

However in the old IR, initializers must be a subset of inputs, even for subgraphs, so we didn't really have much choice other than using the Constant op or hoisting the constants out of the subgraph entirely.

> // A list of named tensor values, used to specify constant inputs of the graph.
>   // Each TensorProto entry must have a distinct name (within the list) that
>   // also appears in the input list.
>   // MAY also appear in the input list.
>   repeated TensorProto initializer = 5;

**Comment by guschmue** [comment] 2021-07-26 22:56
So if we read this that on IR3 even subgraphs had initializers in the input list the new onnx change creates a regression.

**Comment by askhade** [comment] 2021-07-26 22:58
Previously ONNX was not raising these issues during checker phase whereas now it is, the actual shape inference\checker code for controlflow ops has not changed in this release. For now, setting full_check = false should exhibit the same behavior as previous releases. Going forward we can refine this logic to handle such cases better.

**Comment by TomWildenhain-Microsoft** [comment] 2021-07-26 23:01
Yeah @askhade fortunately it is just the checker and isn't a big deal.  I'm still completely fine with just disabling the test. 

> So if we read this that on IR3 even subgraphs had initializers in the input list the new onnx change creates a regression.

Well.... you could argue that these models are invalid in IR3 and there is no legal way to include constant initializers in a subgraph of a Loop node.

**Comment by guschmue** [comment] 2021-07-26 23:12
But according to the source code is wasn't only legal - it was required:
https://github.com/onnx/onnx/blob/rel-1.3.0/onnx/onnx.proto3#L251

One could make the case that this wasn't meant to apply to subgraphs.

I think in general we should be very careful not to break backward compatibility. opset-8 is old but we have no idea how many models are in the wild on opset-8.

**Comment by askhade** [comment] 2021-07-26 23:30
The change in this release was to start reporting node level errors when full_check is set to true... One can set full_check=false (which is also the default) and get the same behavior as previous releases. Current onnx change unmasked the loop related preexisting issue. I agree we should support older models.

**Comment by guschmue** [comment] 2021-07-26 23:35
ah, that is good.

**Comment by rajeevsrao** [comment] 2021-07-28 17:04
@TomWildenhain-Microsoft @guschmue please confirm if this can now be considered closed.

**Comment by TomWildenhain-Microsoft** [comment] 2021-07-28 18:17
@rajeevsrao I'm fine with releasing.  As @askhade said, the change in onnx surfaced an (existing) correctness discrepancy between ONNX and tf2onnx.  That discrepancy needs to fixed, but it is my opinion that it does not need to block an ONNX release.  I'm pretty sure the validation check in ONNX here is incorrect and should be updated from (pseudocode):

```python
def validate_loop(loop_node, subgraph):
    N = len(loop_node.inputs) - 2
    assert 2 + len(subgraph.inputs) == N
```

To:

```python
def validate_loop(loop_node, subgraph):
    N = len(loop_node.inputs) - 2
    if IR_VERSION >= 4:
        # IR 4 specifically prohibits subgraphs from having optional inputs
        assert len(subgraph.inputs) == N + 2
        assert subgraph.num_optional_inputs() == 0   # NOTE: I believe this check is actually stricter than the existing checker
    else:
        # IR <= 3 requires all initializers to be optional inputs
        max_positional_inputs = len(subgraph.inputs)
        min_posiitonal_inputs = max_positional_inputs - subgraph.num_trailing_optional_inputs()
        assert min_posiitonal_inputs <= N + 2 <= max_positional_inputs
```

I'd be in favor of continuing with the release and opening an issue with ONNX to fix in the next version.  @guschmue, @askhade does that seem good?

**Comment by guschmue** [comment] 2021-07-28 18:18
yes, good for me!

**Comment by askhade** [comment] 2021-07-28 18:27
yes, we should be fixed in the next version.

**Closed** 2021-07-28 23:29 UTC
