### ISSUE TITLE
Tensorflow op XlaGather, XlaDot, PreventGradient and StatefulPartitionedCall not supported

### ISSUE THREAD

**Issue by pratima1159** [onnx/tensorflow-onnx#1601] opened 2021-07-08 12:54 UTC
Describe the bug
I am trying to convert a Tensorflow SavedModel (saved_model.pb) to onnx with:

`python3 -m tf2onnx.convert --saved-model liquidity_module/transaction_model --opset 14 --output trans_model.onnx --fold_const --tag serve
` 
The original model was a [flax model](https://github.com/google/flax) converted to TensorFlow with [jax2tf](https://github.com/google/jax/tree/main/jax/experimental/jax2tf)

Urgency
None

System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.15.7 
- Tensorflow Version: 2.7.0-dev20210706 
- Python version: 3.8
- tf2onnx version: 1.9.1

Error Message
```
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py:127: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2021-07-07 10:25:29,383 - INFO - Signatures found in model: [serving_default].
2021-07-07 10:25:29,383 - WARNING - '--signature_def' not specified, using first signature: serving_default
2021-07-07 10:25:29,384 - INFO - Output names: ['output_0', 'output_1', 'output_2', 'output_3', 'output_4']
WARNING:tensorflow:From /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tf2onnx/tf_loader.py:662: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2021-07-07 10:25:29,574 - WARNING - From /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tf2onnx/tf_loader.py:662: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2021-07-07 10:25:29,719 - INFO - Using tensorflow=2.7.0-dev20210706, onnx=1.9.0, tf2onnx=1.9.1/8e8c23
2021-07-07 10:25:29,720 - INFO - Using opset <onnx, 14>
2021-07-07 10:25:29,722 - INFO - Computed 0 values for constant folding
2021-07-07 10:25:29,972 - INFO - Computed 0 values for constant folding
2021-07-07 10:25:30,158 - ERROR - Tensorflow op [XlaGather_8: XlaGather] is not supported
2021-07-07 10:25:30,159 - ERROR - Tensorflow op [XlaGather_6: XlaGather] is not supported
2021-07-07 10:25:30,160 - ERROR - Tensorflow op [XlaGather_4: XlaGather] is not supported
2021-07-07 10:25:30,161 - ERROR - Tensorflow op [XlaGather_2: XlaGather] is not supported
2021-07-07 10:25:30,163 - ERROR - Tensorflow op [XlaGather_14: XlaGather] is not supported
2021-07-07 10:25:30,165 - ERROR - Tensorflow op [XlaGather_13: XlaGather] is not supported
2021-07-07 10:25:30,166 - ERROR - Tensorflow op [XlaGather_12: XlaGather] is not supported
2021-07-07 10:25:30,168 - ERROR - Tensorflow op [XlaGather_10: XlaGather] is not supported
2021-07-07 10:25:30,169 - ERROR - Tensorflow op [XlaGather_1: XlaGather] is not supported
2021-07-07 10:25:30,171 - ERROR - Tensorflow op [XlaGather: XlaGather] is not supported
2021-07-07 10:25:30,172 - ERROR - Tensorflow op [BitwiseAnd: BitwiseAnd] is not supported
2021-07-07 10:25:30,176 - ERROR - Tensorflow op [XlaGather_9: XlaGather] is not supported
2021-07-07 10:25:30,178 - ERROR - Tensorflow op [XlaGather_7: XlaGather] is not supported
2021-07-07 10:25:30,181 - ERROR - Tensorflow op [XlaGather_5: XlaGather] is not supported
2021-07-07 10:25:30,183 - ERROR - Tensorflow op [XlaGather_3: XlaGather] is not supported
2021-07-07 10:25:30,185 - ERROR - Tensorflow op [XlaGather_11: XlaGather] is not supported
2021-07-07 10:25:30,187 - ERROR - Tensorflow op [XlaDot_2: XlaDot] is not supported
2021-07-07 10:25:30,187 - ERROR - Tensorflow op [XlaDot_1: XlaDot] is not supported
2021-07-07 10:25:30,188 - ERROR - Tensorflow op [XlaDot: XlaDot] is not supported
2021-07-07 10:25:30,188 - ERROR - Tensorflow op [XlaDot_3: XlaDot] is not supported
2021-07-07 10:25:30,189 - ERROR - Tensorflow op [XlaDot_4: XlaDot] is not supported
2021-07-07 10:25:30,189 - ERROR - Tensorflow op [XlaDot_5: XlaDot] is not supported
2021-07-07 10:25:30,192 - ERROR - Tensorflow op [XlaDot_8: XlaDot] is not supported
2021-07-07 10:25:30,193 - ERROR - Tensorflow op [XlaDot_9: XlaDot] is not supported
2021-07-07 10:25:30,194 - ERROR - Tensorflow op [PreventGradient_3: PreventGradient] is not supported
2021-07-07 10:25:30,194 - ERROR - Tensorflow op [XlaDot_7: XlaDot] is not supported
2021-07-07 10:25:30,196 - ERROR - Tensorflow op [PreventGradient_2: PreventGradient] is not supported
2021-07-07 10:25:30,196 - ERROR - Tensorflow op [XlaGather_15: XlaGather] is not supported
2021-07-07 10:25:30,197 - ERROR - Tensorflow op [PreventGradient_1: PreventGradient] is not supported
2021-07-07 10:25:30,197 - ERROR - Tensorflow op [XlaDot_10: XlaDot] is not supported
2021-07-07 10:25:30,197 - ERROR - Tensorflow op [PreventGradient: PreventGradient] is not supported
2021-07-07 10:25:30,198 - ERROR - Unsupported ops: Counter({'XlaGather': 16, 'XlaDot': 10, 'PreventGradient': 4, 'BitwiseAnd': 1})
2021-07-07 10:25:30,224 - ERROR - Tensorflow op [StatefulPartitionedCall: StatefulPartitionedCall] is not supported
2021-07-07 10:25:30,225 - ERROR - Unsupported ops: Counter({'StatefulPartitionedCall': 1})
2021-07-07 10:25:30,226 - INFO - Optimizing ONNX model
2021-07-07 10:25:30,296 - INFO - After optimization: Identity -10 (10->0)
2021-07-07 10:25:30,299 - INFO - 
2021-07-07 10:25:30,299 - INFO - Successfully converted TensorFlow model liquidity_module/transaction_model to ONNX
2021-07-07 10:25:30,299 - INFO - Model inputs: ['inputs']
2021-07-07 10:25:30,299 - INFO - Model outputs: ['output_0', 'output_1', 'output_2', 'output_3', 'output_4']
2021-07-07 10:25:30,299 - INFO - ONNX model is saved at trans_model.onnx

```

Additional information:
The model signature obtained from

`saved_model_cli show --dir model_dir --all`

```
[MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['inputs'] tensor_info:
        dtype: DT_FLOAT
        shape: (12, 1, 9)
        name: serving_default_inputs:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output_0'] tensor_info:
        dtype: DT_FLOAT
        shape: (1, 2)
        name: StatefulPartitionedCall:0
    outputs['output_1'] tensor_info:
        dtype: DT_FLOAT
        shape: (1)
        name: StatefulPartitionedCall:1
    outputs['output_2'] tensor_info:
        dtype: DT_FLOAT
        shape: (1, 12, 2)
        name: StatefulPartitionedCall:2
    outputs['output_3'] tensor_info:
        dtype: DT_FLOAT
        shape: (1, 12, 1)
        name: StatefulPartitionedCall:3
    outputs['output_4'] tensor_info:
        dtype: DT_INT32
        shape: (2)
        name: StatefulPartitionedCall:4](url)
```

**Comment by guschmue** [comment] 2021-07-09 16:17
I guess jax is using xla ops - we don't support those.
Maybe not impossible to add support for those. Kind of a interesting thing to think about since to my knowledge there is no good inference solution for jax.
We'll take a look at what it would take.

**Comment by pratima1159** [comment] 2021-07-13 16:02
We would be glad to assist. Looking forward to hearing what you conclude.

**Comment by guschmue** [comment] 2021-07-19 20:08
Let me try one of those xla ops and see how that goes.

**Comment by guschmue** [comment] 2021-07-20 22:43
Looking at this a little closer: ```jax2tf.convert``` has an argument  ```enable_xla``` and if you set this to False (by default its enabled)  things are converting for me, Would that be sufficient ?

For example the flex CNN example you can convert like below. jax2tf has some examples how to get jax models to tflite and they do exactly the same.

```
from typing import Sequence

import jax
import jax.numpy as jnp
import flax.linen as nn
from jax.experimental import jax2tf

import numpy as np
import tensorflow as tf

import tf2onnx

class CNN(nn.Module):
    @nn.compact
    def __call__(self, x):
        x = nn.Conv(features=32, kernel_size=(3, 3))(x)
        x = nn.relu(x)
        x = nn.avg_pool(x, window_shape=(2, 2), strides=(2, 2))
        x = nn.Conv(features=64, kernel_size=(3, 3))(x)
        x = nn.relu(x)
        x = nn.avg_pool(x, window_shape=(2, 2), strides=(2, 2))
        x = x.reshape((x.shape[0], -1))  # flatten
        x = nn.Dense(features=256)(x)
        x = nn.relu(x)
        x = nn.Dense(features=10)(x)
        x = nn.log_softmax(x)
        return x


model = CNN()
x = jnp.ones((32, 64, 64, 10))  # (N, H, W, C) format
variables = model.init(jax.random.PRNGKey(0), x)

def predict(x):
  return model.apply(variables, x)

output = predict(x)
print(output)

OUT = "/tmp/j"
input_signature = [tf.TensorSpec([32, 64, 64, 10], tf.float32)]

# Save a function that can take scalar inputs.
func = tf.function(jax2tf.convert(predict, enable_xla=False), autograph=False,
                   jit_compile=True, input_signature=input_signature)

_, _ = tf2onnx.convert.from_function(
    func, input_signature=input_signature, opset=13, output_path=OUT + ".onnx")
```

**Comment by guschmue** [comment] 2021-07-21 17:11
Played some more with this by trying a huggingface jax model:
```
NotImplementedError: Call to scatter cannot be converted with enable_xla=False.
```
Maybe we need to do the xla thing.

**Comment by guschmue** [comment] 2021-08-23 14:11
In general using jax2tf with enable_xla=False should work for most models.
Closing this issue for now. Please re-open if this does not resolve your issue.

**Closed by guschmue** 2021-08-23 14:11 UTC

**Comment by YusukeSuzuki** [comment] 2022-02-22 07:01
In case of converting `nn.Model` into `tf.SavedModel` for onnx use, I use `saved_model_lib.convert_and_save_model` with arguments described below code. Errors are caused by XLA compile and gradients ommiting.

```
from jax.experimental.jax2tf.examples import saved_model_lib

# ...

saved_model_lib.convert_and_save_model(
    predict_func, params, 'tf_model',
    input_signatures=[tf.TensorSpec(shape=(None, 28*28), dtype=tf.float32)],
    polymorphic_shapes='(b, ...)',
    with_gradient=True,
    enable_xla=False,
    compile_model=False,
    )  
```

**Comment by garymm** [comment] 2022-03-11 18:04
@YusukeSuzuki if the error is coming from `jax2tf`, please file an issue against JAX. If the issue is coming during `tf2onnx` please open a new issue in this repo with more details.

**Comment by YusukeSuzuki** [comment] 2022-03-17 03:36
@garymm It's not error or problem. It's workaround for original issue.

**Comment by guschmue** [comment] 2022-03-17 19:02
perfect, thanks!!
