### ISSUE TITLE
[ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:model/multi_category_encoding/AsString : No Op registered for AsString with domain_version of 9

### ISSUE THREAD

**Issue by hanzigs** [onnx/tensorflow-onnx#1645] opened 2021-08-05 00:25 UTC
Below code works perfect when run in python file (python==3.9.5, tensorflow==2.5.0, keras2onnx==1.7.0, onnxruntime==1.8.0,
keras==2.4.3, tf2onnx==1.9.1)
```
autoKeras_model = StructuredDataClassifier(max_trials=MaxTrials)
autoKeras_model.fit(x=X_train, y=y_train, validation_data=(X_valid, y_valid), epochs=Epochs, verbose=1)
ExportedautoKeras_model = autoKeras_model.export_model()

onnx_model, _ = tf2onnx.convert.from_keras(ExportedautoKeras_model )
content = onnx_model.SerializeToString()
sess = onnxruntime.InferenceSession(content)
```
Same code inside Flask App, InferenceSession throws error
```
sess = onnxruntime.InferenceSession(content)

  File "C:\Users\plg\Anaconda3\envs\automl04augpy395elk7120\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\plg\Anaconda3\envs\automl04augpy395elk7120\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 312, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:model/multi_category_encoding/AsString : No Op registered for AsString with domain_version of 9
I am mainly after input_name
```
If that's a converter bug, how should I find the correct opset? (I have tried opset from 9 to 13, all throws error) then why that error not raised in standalone run?

Any help please, Thanks

**Comment by guschmue** [comment] 2021-08-05 00:29
Looks we don't support the AsString() op. Let me check if we can handle this in the converter.

**Comment by hanzigs** [comment] 2021-08-05 00:32
Not sure how it works when executed codes individually, same not working when run in flask application. Checked all the packages as well.

**Comment by hanzigs** [comment] 2021-08-05 06:03
Is there a work around like custom op till we get the converter update please, Thanks

**Comment by guschmue** [comment] 2021-08-05 20:17
I have some code that maps AsString to ONNX case which kind of works but doesn't honor some attribute AsString has.
But maybe its good enough for autokeras. If it works for autokeras I'll send a PR.

**Comment by guschmue** [comment] 2021-08-06 14:52
worked for me for the structured_classifier example so we merged a PR:
https://github.com/onnx/tensorflow-onnx/pull/1648

You can try with 
```
pip install git+https://github.com/onnx/tensorflow-onnx
```

**Comment by hanzigs** [comment] 2021-08-06 20:40
@guschmue Thank you very much for quick response

Now I am getting this error, 
(python==3.9.5, tensorflow==2.5.0, tf2onnx==1.10.0)
```
sess = onnxruntime.InferenceSession(content)

  File "C:\Users\plg\Anaconda3\envs\automl07augpy395elk7120\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)

  File "C:\Users\plg\Anaconda3\envs\automl07augpy395elk7120\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 312, in _create_inference_session

    sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:model/multi_category_encoding/string_lookup_1/None_lookup_table_find/LookupTableFindV2 : No Op registered for LookupTableFindV2 with domain_version of 9
```

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-06 22:28
What are the shapes and dtypes of `X_train`, `y_train`, `X_valid`, `y_valid`?  Can you upload a zipped saved model of the keras model?  Sorry I've never used autokeras before.

**Comment by hanzigs** [comment] 2021-08-06 22:46
X_train, y_train, X_valid, y_valid , (1056, 16) (1056,) (191, 16) (191,) respectively, all numpy.ndarray
(python==3.9.5, tensorflow==2.5.0, tf2onnx==1.10.0, onnxruntime==1.8.0)
creating model is simple, I can attach the pickles of X_train, y_train, X_valid, y_valid, May I know where please
```
pip install autokeras==1.0.15
from autokeras import StructuredDataClassifier
akmodel = StructuredDataClassifier(max_trials=10)
akmodel.fit(x=X_train, y=y_train, validation_data=(X_valid, y_valid), epochs=100)
autoKeras_model = akmodel.export_model()

onnx_model, _ = tf2onnx.convert.from_keras(model)
content = onnx_model.SerializeToString()
sess = onnxruntime.InferenceSession(content)
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
```

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-06 22:48
Can you upload the pickles to OneDrive/GoogleDrive/Dropbox and post a link?  Are those all np.int32 or np.float32?

**Comment by hanzigs** [comment] 2021-08-06 22:50
yes they are

https://drive.google.com/drive/folders/1HfB00dOuk-awSmIrSg92hmJFYzTpQNCr?usp=sharing

attached in google drive, you can open with
```
import pickle
with open('filename','rb') as f: arrayname1 = pickle.load(f)
```

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-06 22:52
Great, I just requested access to the drive link.

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-06 23:24
I just run conversion and it works for me.  The resulting model runs in ORT and produces results.  However, my model does not contain AsString, maybe I'm using a different version of autokeras.  My converted onnx model looks like this:

![image](https://user-images.githubusercontent.com/67606533/128579614-792586ba-4946-43da-a3f4-23dc5154bb2f.png)

**Comment by hanzigs** [comment] 2021-08-06 23:29
Actually as said before model created successfully in python file, and InferenceSession creates successful in python file

InferenceSession throws error in flask app

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-06 23:31
Ah, so sorry.  Didn't catch that.  What version of onnxruntime does the flask application use?

**Comment by hanzigs** [comment] 2021-08-06 23:31
Same kind of issue as in #1228

**Comment by hanzigs** [comment] 2021-08-06 23:32
All same versions

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-06 23:40
> Same kind of issue as in #1228

Can you please elaborate on this?  Are you getting a "Default value of table lookup must be const." error?  Are you running the conversion code within flask too, or just onnxruntime?  You can save both the keras saved model and the onnx model with:

```python
ExportedautoKeras_model.save("autokerasmodel")
onnx_model, _ = tf2onnx.convert.from_keras(ExportedautoKeras_model, output_path="autokeras.onnx")
```

I find it very surprising that you get different results in flask.  Is your flask running from a different virtualenv?  Are you sure your autokeras version is the same?

**Comment by hanzigs** [comment] 2021-08-06 23:45
Yes I am using same model for conversion to onnx

Inside  flask, creating the model and converting it, and trying to get the session results all at once

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-06 23:52
I think it is very likely that the keras models you get in flask and the plain python script are different.  Can you please add this line:
`ExportedautoKeras_model.save("autokerasmodel")`
and zip the results of the python and flask scripts?

**Comment by hanzigs** [comment] 2021-08-06 23:56
Inside Flask App, I have two functions, one model creation and passing the model to onnxconverter function, not sure is that a issue, 
now will try to put both in same function,

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-06 23:58
That should not be an issue.  Again to confirm, are you using the same virtualenv for flask as the python script?

**Comment by hanzigs** [comment] 2021-08-06 23:59
yes, python and flask are in same env

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-07 00:00
Is the training data you are using (X_train, y_train, X_valid, y_valid) the same values for both?

**Comment by hanzigs** [comment] 2021-08-07 00:02
Also in normal python file, onnxConversion and InferenceSession works
But when i do prediction from onnx model it throws error
like
```
content = ONNXModel.SerializeToString()
sess = onnxruntime.InferenceSession(content)
input_name = sess.get_inputs()[0].name 
label_name = sess.get_outputs()[0].name
pred_onnx = sess.run([label_name], {input_name: test_record})[0]
```

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-07 00:04
Are you able to capture the keras saved model from flask?

**Comment by hanzigs** [comment] 2021-08-07 00:05
Can you please confirm the prediction test.

**Comment by hanzigs** [comment] 2021-08-07 00:05
yes i can

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-07 00:10
> Can you please confirm the prediction test.

I am able to successfully run predictions using the onnx model I have generated.  The model is uploaded to the shared drive folder as as `autokeras_tw.onnx`

> yes i can

Awesome.  Please capture and upload the keras saved models and converted onnx models for flask and the python script and upload them to the Google Drive folder as `autokeras_flask.zip`, `autokeras_flask.onnx`, `autokeras_python.zip`, `autokeras_python.onnx`.  If I have those, I may be able to reproduce the issue.  So far, I can't reproduce it at all.

**Comment by hanzigs** [comment] 2021-08-07 00:19
I have uploaded a ONNXmodel.onnx in the drive, can you please try to create a session from it

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-07 00:29
Both models give me the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tomwi\AppData\Local\Programs\Python\Python39\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\tomwi\AppData\Local\Programs\Python\Python39\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 310, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from C:\Users\tomwi\Downloads\ONNXModel.onnx failed:This is an invalid model. Error in Node:model/multi_category_encoding/string_lookup_1/None_lookup_table_find/LookupTableFindV2 : No Op registered for LookupTableFindV2 with domain_version of 9
```

But I will need a saved model to diagnose the cause of the conversion failure.  If you are not able to upload a saved model due to privacy/security concerns, I can try to walk through the debugging on your end, or we can wait for @guschmue who might have better luck reproducing the issue with autokeras.

**Comment by hanzigs** [comment] 2021-08-07 00:30
Yes, thats the one

**Comment by hanzigs** [comment] 2021-08-07 00:39
I have printed the onnx model from flask run and saved in a file "onnxfile.txt" and uploaded in the drive, if that helps

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-07 00:48
So the issue is here:
![image](https://user-images.githubusercontent.com/67606533/128582480-bc9b4f7d-7c3c-43cd-bf50-8b2d627b2787.png)
The LookupTableFindV2 op shouldn't be in the final model.  It should be removed by: https://github.com/onnx/tensorflow-onnx/blob/04d24880751e4f753623d9097819e793e75962a9/tf2onnx/custom_opsets/onnx_ml.py#L67

Try to determine whether that handler is running and if it is entering that conditional.

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-07 00:53
Also is anything printed to the console during conversion, and are any exceptions raised?  Change the log level before conversion with:
`import logging`
`logging.basicConfig(level=logging.INFO)`

**Comment by hanzigs** [comment] 2021-08-07 01:02
Here is the full error from flask
error before printing the model
```
ERROR:tf2onnx.tf_loader:Could not find table resource to replace placeholder model/multi_category_encoding/string_lookup_1/None_lookup_table_find/LookupTableFindV2/table_handle
INFO:tf2onnx.tfonnx:Using tensorflow=2.5.0, onnx=1.10.0, tf2onnx=1.10.0/04d248
INFO:tf2onnx.tfonnx:Using opset <onnx, 9>
WARNING:tf2onnx.shape_inference:Cannot infer shape for model/multi_category_encoding/string_lookup_1/None_lookup_table_find/LookupTableFindV2: model/multi_category_encoding/string_lookup_1/None_lookup_table_find/LookupTableFindV2:0
WARNING:tf2onnx.shape_inference:Cannot infer shape for model/multi_category_encoding/Cast_1: model/multi_category_encoding/Cast_1:0
INFO:tf2onnx.tf_utils:Computed 0 values for constant folding
WARNING:tf2onnx.onnx_opset.tensor:ONNX does not support precision, scientific and fill attributes for AsString
ERROR:tf2onnx.tfonnx:Failed to convert node 'model/multi_category_encoding/string_lookup_1/None_lookup_table_find/LookupTableFindV2' (fct=<bound method LookupTableFind.version_8 of <class 'tf2onnx.custom_opsets.onnx_ml.LookupTableFind'>>)
'OP=LookupTableFindV2\nName=model/multi_category_encoding/string_lookup_1/None_lookup_table_find/LookupTableFindV2\nInputs:\n\tmodel/multi_category_encoding/string_lookup_1/None_lookup_table_find/LookupTableFindV2/table_handle:0=Placeholder, [], 7\n\tmodel/multi_category_encoding/AsString:0=Cast, [-1, 1], 8\n\tmodel/multi_category_encoding/string_lookup_1/None_lookup_table_find/LookupTableFindV2/default_value:0=Const, [], 7\nOutpus:\n\tmodel/multi_category_encoding/string_lookup_1/None_lookup_table_find/LookupTableFindV2:0=None, 7'
Traceback (most recent call last):
  File "C:\Users\pl\Anaconda3\envs\AutoMLIntuitionAug2021py395elk7120\lib\site-packages\tf2onnx\tfonnx.py", line 292, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
  File "C:\Users\pl\Anaconda3\envs\AutoMLIntuitionAug2021py395elk7120\lib\site-packages\tf2onnx\custom_opsets\onnx_ml.py", line 34, in version_8
    utils.make_sure(shared_name is not None, "Could not determine table shared name for node %s", node.name)
  File "C:\Users\pl\Anaconda3\envs\AutoMLIntuitionAug2021py395elk7120\lib\site-packages\tf2onnx\utils.py", line 260, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: Could not determine table shared name for node model/multi_category_encoding/string_lookup_1/None_lookup_table_find/LookupTableFindV2
INFO:tf2onnx.optimizer:Optimizing ONNX model
INFO:tf2onnx.optimizer:After optimization: Const -19 (29->10), Identity -2 (2->0)
```
this error during creating Session
```
ERROR:AutoMLWebApi:500 Internal Server Error: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:model/multi_category_encoding/string_lookup_1/None_lookup_table_find/LookupTableFindV2 : No Op registered for LookupTableFindV2 with domain_version of 9
Traceback (most recent call last):
  File "C:\pl\AutoML\AutoMLIntuitionJuly2021py395elk7120\AutoMLWebApi.py", line 88, in autoML
    result = AutoMLTrainer.train(tenant_id, data)
  File "C:\pl\AutoML\AutoMLIntuitionJuly2021py395elk7120\AutoMLTrainer.py", line 903, in train
    uploadToElastic(es,
  File "C:\pl\AutoML\AutoMLIntuitionJuly2021py395elk7120\AutoMLUtils.py", line 3927, in uploadToElastic
    sess = onnxruntime.InferenceSession(content)
  File "C:\Users\pl\Anaconda3\envs\AutoMLIntuitionAug2021py395elk7120\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\pl\Anaconda3\envs\AutoMLIntuitionAug2021py395elk7120\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 312, in _create_inference_session 
    sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:model/multi_category_encoding/string_lookup_1/None_lookup_table_find/LookupTableFindV2 : No Op registered for LookupTableFindV2 with domain_version of 9

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pl\Anaconda3\envs\AutoMLIntuitionAug2021py395elk7120\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pl\Anaconda3\envs\AutoMLIntuitionAug2021py395elk7120\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\pl\AutoML\AutoMLIntuitionJuly2021py395elk7120\AutoMLWebApi.py", line 96, in autoML
    abort(500, err)
  File "C:\Users\pl\Anaconda3\envs\AutoMLIntuitionAug2021py395elk7120\lib\site-packages\werkzeug\exceptions.py", line 940, in abort
    _aborter(status, *args, **kwargs)
  File "C:\Users\pl\Anaconda3\envs\AutoMLIntuitionAug2021py395elk7120\lib\site-packages\werkzeug\exceptions.py", line 923, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:model/multi_category_encoding/string_lookup_1/None_lookup_table_find/LookupTableFindV2 : No Op registered for LookupTableFindV2 with domain_version of 9
INFO:werkzeug:127.0.0.1 - - [07/Aug/2021 10:58:40] "POST /tenant_id/train HTTP/1.1" 500 -
```

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-07 01:08
`Could not determine table shared name for node` oh haha you should have lead with that.  Is that what you meant by "Same kind of issue as in #1228".  #1228 had a few error messages involved.

tf2onnx isn't finding the values for the lookup table.

Try this: make a saved model, then convert it with `python -m tf2onnx.convert --saved-model mysavedmodel --output model.onnx` from the command line.

**Comment by hanzigs** [comment] 2021-08-07 01:11
actually this will used for deployment, this procedure should be followed, if i make it work from cmd line will not be useful

**Comment by hanzigs** [comment] 2021-08-07 01:13
even saving model to disk is not useful, coz this will be deployed in docker container

**Comment by hanzigs** [comment] 2021-08-07 01:17
is there a workaround for that please

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-07 01:17
Ok, then we need to find the data in the keras model's lookup table without saving it.  The challenge here is that the lookup table is held inside the TF runtime and it can be challenging to extract it.  Normally a second copy is stored on the keras model itself, and this method searches for it:

https://github.com/onnx/tensorflow-onnx/blob/04d24880751e4f753623d9097819e793e75962a9/tf2onnx/tf_loader.py#L406

You'll need to find where the lookup table info is stored on the keras model.

**Comment by hanzigs** [comment] 2021-08-07 01:18
ok, how to do that?

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-07 01:19
Can you attach a debugger?

**Comment by hanzigs** [comment] 2021-08-07 01:19
is that mean, the flask in debug mode?

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-07 01:20
Are you using VSCode or another IDE?

**Comment by hanzigs** [comment] 2021-08-07 01:21
yeah VSCode

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-07 01:24
Great.  Launch the app in debug mode:
https://code.visualstudio.com/docs/python/tutorial-flask#_run-the-app-in-the-debugger

Drop a breakpoint after model creation.  Use the debug console to explore the model's attributes... sorry it's a bit tricky.

**Comment by hanzigs** [comment] 2021-08-07 01:27
yeah
here is the screen shot, what to be checked there
![image](https://user-images.githubusercontent.com/30790120/128583693-2eaf14e9-79c5-42ef-97bf-980553400d1e.png)

**Comment by hanzigs** [comment] 2021-08-07 01:29
do I need to step into from_keras() and go to this function def _get_hash_table_info_from_trackable(trackable, table_names, key_dtypes, value_dtypes, ?

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-07 01:30
One moment, I'm checking something.

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-07 01:46
In the model, you want to find the table's resource handle and dtype.  The resource handle is key, since it lets you request the lookup table's contents from tensorflow.  For mine, it is stored on the lookup table layer:

![image](https://user-images.githubusercontent.com/67606533/128584116-e186183d-b8d2-4677-bede-2e323dbf69e8.png)

Going a few layers deep, I find:
![image](https://user-images.githubusercontent.com/67606533/128584130-61c36379-c78f-4f74-aa27-024f685dd9c7.png)

You really shouldn't have to find it manually since we do a pretty comprehensive search, but autokeras must put it somewhere we don't expect.

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-07 01:46
If you find it, we can update our search to find it automatically for you based on the attributes it end up on.

**Comment by hanzigs** [comment] 2021-08-07 01:49
OK, will try to find that and get back

**Comment by hanzigs** [comment] 2021-08-07 01:58
whether these are those
![image](https://user-images.githubusercontent.com/30790120/128584437-f51bb174-7f26-406d-a55d-b1bbe39a29c5.png)

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-07 02:09
Those are output nodes.  They are not tables.  I might be able to improve our table loading.  Give me 45 minutes.

**Comment by hanzigs** [comment] 2021-08-07 02:20
Here is some Error Lines

![image](https://user-images.githubusercontent.com/30790120/128584895-e674aaf7-c2e4-4425-aae3-93a424bc1d04.png)


![image](https://user-images.githubusercontent.com/30790120/128584884-ad181144-abfb-4cd9-a031-bc45459dec9c.png)

**Comment by hanzigs** [comment] 2021-08-07 02:30
another one
![image](https://user-images.githubusercontent.com/30790120/128585095-45fa7144-6fbe-45b8-949c-db113bb07a49.png)


![image](https://user-images.githubusercontent.com/30790120/128585052-38d37485-4bf1-4f8a-9b9f-5b5cc6093bb9.png)

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-07 02:57
Unfortunately what I tried didn't work.  I still need either a shared_name or resource_handle for the tensorflow backend to give me the values stored in the table.  The keras model must have them somewhere because it needs to pull those values to save the model.  The existing search code actually traces the model save code to find the resources, but they must be overriding the defaults or something.  Hard for me to say without seeing the model.

**Comment by hanzigs** [comment] 2021-08-07 03:02
the key value for the search should be "resource_handle" is it?

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-07 03:29
> the key value for the search should be "resource_handle" is it?

Or shared_name.  Actually shared_name is slightly better.  Ideally we want both.  They are normally next to each other, and they might start with an underscore prefix ("_shared_name").

I've got another idea that I actually think will work but it's late so I'll try it tomorrow/Monday.

**Comment by hanzigs** [comment] 2021-08-07 07:01
I found these few things, there is _shared_name and _handle_name
Each of the _undeduplicated_weights different names for each

![image](https://user-images.githubusercontent.com/30790120/128591143-14e5c9c6-30f0-4f1a-8969-2ae6328855ce.png)

![image](https://user-images.githubusercontent.com/30790120/128591170-5db63d8c-a6a9-4359-9c3a-9f64795fa34a.png)

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-08 03:45
#1654 will hopefully fix it automatically.  Try it with:
`pip uninstall tf2onnx`
`pip install git+https://github.com/onnx/tensorflow-onnx@tom/keras_hash_tables`

The improved method grabs the resource handle from graph captures and makes up a shared_name if it fails to find one in the model.

**Comment by hanzigs** [comment] 2021-08-08 06:38
That was perfect, It worked as expected, Thank you very much, and greatly appreciated for the support.

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-08 20:10
Excellent.  And @hanzigs have you confirmed that the model loads in onnx runtime and produces correct results when run on the validation data?

**Comment by hanzigs** [comment] 2021-08-08 22:30
Yes, python model and onnx model reproduces the same expected results
```
![image](https://user-images.githubusercontent.com/30790120/128647515-ccf08117-8740-472b-804d-1632f7ec9391.png)

```

**Comment by hanzigs** [comment] 2021-08-08 23:28
May I know how to save onnx model as single onnx file?
when I use 
```
keras2onnx.save_model(ONNXModel, os.path.join(Location, ModelName))
```
It saves as single file, but the prediction result varying between saved model and original model

**Comment by hanzigs** [comment] 2021-08-08 23:54
May I know how to save the tf2onnx model
I tried these two ways
```
onnx.save_model(ONNXModel, os.path.join(Location, ModelName))

keras2onnx.save_model(ONNXModel, os.path.join(Location, ModelName))
```
But the prediction results are different between saved model and original model

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-09 01:12
Awesome!  Thanks for helping us debug this.

**Comment by hanzigs** [comment] 2021-08-09 02:17
please let me know when this is ready in pip install tf2onnx

**Comment by hanzigs** [comment] 2021-08-09 03:41
Hope these warnings doesn't affect anythings
```
INFO:tf2onnx.tfonnx:Using tensorflow=2.5.0, onnx=1.10.0, tf2onnx=1.10.0/32d758
INFO:tf2onnx.tfonnx:Using opset <onnx, 9>
WARNING:tf2onnx.shape_inference:Cannot infer shape for model/multi_category_encoding/string_lookup_1/None_lookup_table_find/LookupTableFindV2: model/multi_category_encoding/string_lookup_1/None_lookup_table_find/LookupTableFindV2:0
WARNING:tf2onnx.shape_inference:Cannot infer shape for model/multi_category_encoding/Cast_1: model/multi_category_encoding/Cast_1:0
INFO:tf2onnx.tf_utils:Computed 0 values for constant folding
WARNING:tf2onnx.onnx_opset.tensor:ONNX does not support precision, scientific and fill attributes for AsString
INFO:tf2onnx.optimizer:Optimizing ONNX model
INFO:tf2onnx.optimizer:After optimization: Const -20 (29->9), Identity -2 (2->0)
```

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-09 18:09
Awwww, thought we had fixed this.  The models from python and flask are different.  Keep in mind that autokeras can choose very different model architectures depending on the data it is given.  I think it is likely you are training the python and flask models on different data.

The "does not support precision, scientific and fill attributes for AsString" might or might not matter depending on how the lookup table is formatted.  Can you upload the converted onnx model from flask again?

**Comment by guschmue** [comment] 2021-08-09 18:48
The warning - we can't handle all attributes from AsString(), ie. instead of float 123. onnx would have float 123.000000. Not sure if it hurts in this case - it might if the category mapper is behind it because the lookup table would have the tf representation. 
int32, int64 should be ok, float might run into issues. 
Not sure autokeras starts using AsString() - for the examples I tried I saw it always used String_To_Number().

**Comment by hanzigs** [comment] 2021-08-09 21:36
Thanks for that, uploaded the converted onnx model in the drive.

Regarding different results, actually I meant the python model in flask and the same model converted to onnx, those two prediction results are different

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-09 21:43
Ah, do you get the same results between the flask keras model and the flask onnx model?

I think you are almost certainly getting different models in flask and python.  I'm not sure why, but I suspect you are giving autokeras different input data or different args.

**Comment by hanzigs** [comment] 2021-08-09 21:47
yeah, here
```
onnx_model, _ = tf2onnx.convert.from_keras(model)
```
This is inside Flask
model is python object, the prediction result is 0.60987216
onnx_model result is 0.5559953
for same test data

**Comment by hanzigs** [comment] 2021-08-09 21:47
Not sure whether those warnings make any difference

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-09 22:05
The category mapper in the model looks like:
![image](https://user-images.githubusercontent.com/67606533/128780013-a60ff184-fc3d-48f4-8eeb-10185bbb2711.png)

That's likely not going to work.  That said, I find the whole thing a little strange since the result is immediately cast back to float.  Seems highly unlikely that this lookup table is useful.  @hanzigs are you using real testing data on this?  Do you find that the TF model produces useful results on non-training data?

Also are you **certain** you are running the python script with the same data, args, and virtual environment as the flask app?

**Comment by hanzigs** [comment] 2021-08-09 22:13
Reg:  same data, args, and virtual environment, yes I'm sure about that. because, this flask app has got 7 models, keras seq, lgbm, xgb, randomforest, extratrees, decisiontree and autokeras, all other 6 models working perfect, same way the data, args are passed, so I'm sure those are correct in flask app.

Reg cast back to float, not sure what's that, but testing data is correct,

May I understand what will be the problem for the above please

**Comment by hanzigs** [comment] 2021-08-09 22:16
There is no complex code happening in autokeras
```
    akmodel = StructuredDataClassifier(max_trials=AK_Hyperparameters['max_trials'])
    akmodel.fit(x=X_train, y=y_train, validation_data=(X_valid, y_valid), epochs=AK_Hyperparameters['epochs'])
    autoKeras_model = akmodel.export_model()
```

**Comment by hanzigs** [comment] 2021-08-09 22:19
Category Fields are normalized using woe transformation, Numeric fields are normalized using MinMaxScalar

**Comment by hanzigs** [comment] 2021-08-09 22:22
Testing data transformation follows the same steps of normalization for prediction

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-09 22:32
The issue is that the input to the CategoryMapper (lookup table) comes from an AsString op in TF, which converts a number to a string.  There is no corresponding op in ONNX, so we convert to a Cast, but that won't necessarily use the same precision.  aka 0.0 becomes "0.0" not "0.00000".  The lookup for 0.0 will return 1 not 5 and the results may be different.  If we were doing int to string, it would be consistent, but float to string is more problematic.

**Closed** 2021-08-09 22:31 UTC

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-09 22:32
> Flask app is bit complex to take out a miniature version, because it is linked the database which is elasticsearch on each and every step, thats why I can't send the flask app code.

Is the data from the database used to train the autokeras model?

**Comment by hanzigs** [comment] 2021-08-09 22:33
Yes it is

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-09 22:33
How does the python script get the data then?  What data does it use?

**Comment by hanzigs** [comment] 2021-08-09 22:34
python elasticsearch client to pull the data

**Comment by TomWildenhain-Microsoft** [comment] 2021-08-09 22:34
Can you pickle the data from each and compare that they are identical?

**Comment by hanzigs** [comment] 2021-08-09 22:34
yes i can

**Comment by hanzigs** [comment] 2021-08-09 22:35
the prediction testing happens from POSTMAN

**Comment by hanzigs** [comment] 2021-08-09 22:38
> The issue is that the input to the CategoryMapper (lookup table) comes from an AsString op in TF, which converts a number to a string. There is no corresponding op in ONNX, so we convert to a Cast, but that won't necessarily use the same precision. aka 0.0 becomes "0.0" not "0.00000". The lookup for 0.0 will return 1 not 5 and the results may be different. If we were doing int to string, it would be consistent, but float to string is more problematic.

But if I build model step by step in a python file by calling only functions of flask app and test, it works fine

**Comment by hanzigs** [comment] 2021-08-09 22:46
Anyway will check that, Thanks for the support, much appreciated, You can close this ticket.

**Comment by hanzigs** [comment] 2021-08-12 02:05
Hi @TomWildenhain-Microsoft 
I have uploaded 3 models in the drive,
Is it possible to check the CategoryMapper cast back to float is in those models. Because all these models giving perfect results, but build from python file using functions from Flask app.
Thanks

**Comment by hanzigs** [comment] 2021-08-12 05:04
I visualized in netron, couldn't find Categorymapper in the 3 models
![image](https://user-images.githubusercontent.com/30790120/129140797-a6e429db-8ee1-4300-8fc2-28543ae1a0f0.png)
Not sure why it's not there

The other model looks
![image](https://user-images.githubusercontent.com/30790120/129140734-13f7f6a0-5a4d-405b-aeab-10f8ba3e446c.png)
Not sure why its simple

previous models have it
![image](https://user-images.githubusercontent.com/30790120/129140849-0b10cf3d-cd21-464e-b709-cacbae040d6a.png)
![image](https://user-images.githubusercontent.com/30790120/129140856-c415e487-bc04-4b42-8bfb-28c708e72fb0.png)

**Comment by hanzigs** [comment] 2021-08-17 06:40
Hi @TomWildenhain-Microsoft 
whether 'tom/keras_hash_tables' branch not available for installation?
Thanks

**Comment by hanzigs** [comment] 2021-08-23 04:49
Hi,
Added a Colab notebook with data and autokeras model building with the error (shared in the drive)
https://colab.research.google.com/drive/1DqlJgGZuKf5nev9G6Do7DYEMEU4aAQhy

https://drive.google.com/drive/folders/1HfB00dOuk-awSmIrSg92hmJFYzTpQNCr?usp=sharing

Let me know whether its possible to convert, Thanks
