### ISSUE TITLE
Conversion Optimizations

### ISSUE THREAD

**Issue by solarflarefx** [onnx/tensorflow-onnx#853] opened 2020-03-19 16:57 UTC
**Describe the issue**
Sometimes when I convert models I get the following messages:
ReferenceError: weakly-referenced object no longer exists
After optimization: no change

I realize that these issues are network specific, but I am trying to understand things at a higher level. 
 What do these messages mean exactly?  Could they result in extra latency in the inference as compared to the original model being converted from?

What would prevent an optimization from occurring? Is there any pre-work that can be done before conversion for a more optimized onnx model? 

**System information**
- OS Platform: Windows 10
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version: 1.2.0, gpu version
- Python version: 3.7
- Visual Studio version (if applicable): 2019
- CUDA/cuDNN version: 10.1
- Tool to convert pb to onnx: tf2onnx 1.5.5
- Version of onnx: 1.6.0
- Version of TensorFlow: 1.14.0, gpu version

**Additional context**
I used the following command to create an ONNX model from a tensorflow frozen graph model (.pb).

python -m tf2onnx.convert --graphdef frozengraph.pb --output model.onnx --opset 11 --fold_const --inputs input_layer:0 --outputs output_layer:0

**Comment by jignparm** [comment] 2020-03-19 23:52
This issue https://github.com/onnx/tensorflow-onnx/issues/845 refers to a run log mentioning a similar error of 'weakly-referenced object'. However, I was not able to reproduce it, using exactly the same TF model.

Possibilities:
* Can you rerun using TF 1.14 CPU version (instead of GPU) to see if this is what's causing the error for you?
* Additionally, could you share a model that can be used to reproduce this error?

**Comment by solarflarefx** [comment] 2020-03-25 03:17
So I tried your suggestion of TF 1.14 CPU and it did not seem to make a difference.  I have attached the pb and onnx of an example file.

As an example, I tried converting this model: http://download.tensorflow.org/models/deeplab_cityscapes_xception71_trainfine_2018_09_08.tar.gz

I notice also that when doing the conversion that there are transposes in various parts of the network.

The command I tried using was: python -m tf2onnx.convert --graphdef frozen_inference_graph.pb --output frozen_inference_graph.onnx --fold_const --opset 11 --inputs ImageTensor:0 --outputs SemanticPredictions:0

I got the following:
ReferenceError: weakly-referenced object no longer exists
2020-03-24 23:00:40,937 - WARNING - Failed to apply fold_constants
ReferenceError: weakly-referenced object no longer exists
2020-03-24 23:00:41,029 - WARNING - Failed to apply loop_optimizer
ReferenceError: weakly-referenced object no longer exists
2020-03-24 23:00:41,197 - WARNING - Failed to apply merge_duplication
ReferenceError: weakly-referenced object no longer exists
2020-03-24 23:00:41,370 - WARNING - Failed to apply remove_identity
ReferenceError: weakly-referenced object no longer exists
2020-03-24 23:00:41,461 - WARNING - Failed to apply remove_back_to_back

**Comment by jignparm** [comment] 2020-03-25 06:31
That's strange, because the same command and model works cleanly for me, without any warnings/errors -- see run log below.

In case your installation is corrupted, can you reinstall your python 3.7 (as well as TF and ONNX packages), and run the TF2ONNX code in master branch of this repository?

### Run Log using deeplab_cityscapes_xception71_trainfine_2018_09_08.tar.gz
```
localadmin@JRP-VM1-WIN-GPU MINGW64 /d/models_deeplab_cityscapes/train_fine
$ python -m tf2onnx.convert --graphdef frozen_inference_graph.pb --output frozen_inference_graph.onnx --fold_const --opset 11 --inputs ImageTensor:0 --outputs SemanticPredictions:0

2020-03-25 06:20:30,255 - WARNING - From D:\jignparmtf2onnx2\tf2onnx\verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2020-03-25 06:20:41,305 - INFO - Using tensorflow=1.14.0, onnx=1.6.0, tf2onnx=1.6.0/82f805
2020-03-25 06:20:41,305 - INFO - Using opset <onnx, 11>
2020-03-25 06:20:48,378 - INFO - Optimizing ONNX model
        2020-03-25 06:21:44,018 - INFO - After optimization: Add -162 (189->27), Cast -17 (29->12), Const -252 (629->377), Gather +8 (4->12), Identity -5 (5->0), Reshape -78 (116->38), Size -1 (4->3), Squeeze -2 (16->14), Transpose -401 (454->53), Unsqueeze -6 (12->6)
2020-03-25 06:21:44,374 - INFO -
2020-03-25 06:21:44,374 - INFO - Successfully converted TensorFlow model frozen_inference_graph.pb to ONNX
2020-03-25 06:21:44,788 - INFO - ONNX model is saved at frozen_inference_graph.onnx
```

**Comment by solarflarefx** [comment] 2020-03-25 12:22
Interesting.  I had pulled the packages from pip.  Are you recommending to pull them from git instead?

It looks like you are doing this on a Windows 10 64-bit system (just like me), but I wanted to confirm.

I am trying to find any other source of difference.  I am doing this with Anaconda creating a unique environment.  I haven't had a problem with this with other projects but do you see any potential issue with this?

**Comment by jignparm** [comment] 2020-03-25 18:41
Only the tf2onnx from GitHub (the rest can be from pip + PyPi). You can clone the GitHub repository and set the PYTHONPATH  environment variable to the root of the local clone (no need to install a package for tf2onnx if you do it this way).

Yes, the run above was using Windows. Also, using Anaconda should be fine -- the run above used Anaconda Python v 3.7.

**Comment by guschmue** [comment] 2020-03-25 18:43
maybe  use ```pip install git+https://github.com/onnx/tensorflow-onnx```

**Comment by solarflarefx** [comment] 2020-03-26 03:20
Wow that did it.  Thank you very much.

2020-03-25 23:13:58,960 - INFO - Using tensorflow=1.14.0, onnx=1.6.0, tf2onnx=1.6.0/557939
2020-03-25 23:13:58,960 - INFO - Using opset <onnx, 11>
2020-03-25 23:14:04,039 - INFO - Optimizing ONNX model
2020-03-25 23:14:42,671 - INFO - After optimization: Add -77 (104->27), Cast -17 (29->12), Const -252 (629->377), Gather +8 (4->12), Identity -5 (5->0), Reshape -78 (116->38), Size -1 (4->3), Squeeze -2 (16->14), Transpose -401 (454->53), Unsqueeze -6 (12->6)
2020-03-25 23:14:42,964 - INFO -
2020-03-25 23:14:42,964 - INFO - Successfully converted TensorFlow model frozen_inference_graph.pb to ONNX
2020-03-25 23:14:43,614 - INFO - ONNX model is saved at frozen_inference_graph.onnx


One question I have after looking through the network is that I still see transposes throughout the network.  For example:
![onnx_converted](https://user-images.githubusercontent.com/45402633/77606795-eadf5c80-6eee-11ea-8e82-47c4ba0de2f7.PNG)

I understand that if not explicitly set to nchw, there will be an extra transpose at the beginning.  But I would not expect these transposes to carry throughout parts of the network.

**Comment by guschmue** [comment] 2020-03-26 13:56
53 left. I'm sure we can get rid of the 2 around SpaceToDepth. Less optimistic about the one after Relu but maybe @jignparm has some magic.

**Comment by jignparm** [comment] 2020-03-26 21:56
I  see 40 transposes in the `deeplab_cityscapes_xception71_trainfine_2018_09_08` onnx model, so maybe the pic above is from another model? @solarflarefx, can you paste a link to the model in the pic?

The transposes around the SpaceToDepth and DepthToSpace ops may be tricky unfortunately, however will investigate!

**Comment by jignparm** [comment] 2020-03-27 08:21
The operators in the model are due to SpaceTo**Batch**ND, being simulated using SpaceTo**Depth** op in Onnx. 

The **Batch** axis is different from the **Depth** axis --unfortunately we need the transpose pairs, and no way to reduce the transposes any further, except by introducing **Batch** ops in Onnx.

Closing this out for now.

**Closed by jignparm** 2020-03-27 08:21 UTC
