### ISSUE TITLE
SyntaxError: invalid syntax for ls saved_model and ls saved_model/my_model tensorflow

### ISSUE THREAD

**Issue by Fahrizal124** [onnx/tensorflow-onnx#1286] opened 2021-01-21 16:46 UTC
File "<ipython-input-33-51ce8f52453d>", line 2
    ls saved_model
       ^
SyntaxError: invalid syntax

**Comment by guschmue** [comment] 2021-01-21 17:16
dupe of https://github.com/onnx/tensorflow-onnx/issues/1285

**Closed by guschmue** 2021-01-21 17:16 UTC
