### ISSUE TITLE
Fill_op for opset 9 causes onnxruntime type mismatch

### ISSUE THREAD

**Issue by jiafatom** [onnx/tensorflow-onnx#391] opened 2019-03-20 00:55 UTC
I am using the following code in the test framework
` def test_fill(self):
        from keras import backend as K
        class_box_scores = K.variable(np.random.random((2, 3)))
        c = 20
        classes_ = K.ones_like(class_box_scores, 'int32') * K.constant(value=c, dtype='int32')
        _ = tf.identity(classes_, name="output")
        input_names_with_port = []
        feed_dict = {}
        output_names_with_port = ["output:0"]
        self.run_test_case(feed_dict, input_names_with_port, output_names_with_port, rtol=1e-06)`

then it causes onnx runtime error when I using **opset=9**
RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : Load model from C:\Users\jiafa\AppData\Local\Temp\tmpkn0tod4m\test_simple_while_loop\test_simple_while_loop.onnx failed:Type Error: Type parameter (T) bound to different types (tensor(float) and tensor(int32) in node (mul).

**Comment by nbcsm** [comment] 2019-03-20 03:40
it seems to be caused by onnx version.
we will add check for onnx version, and skip attributes check for unknown ops.

**Comment by nbcsm** [comment] 2019-03-21 12:43
@jiafatom, could you try again please? thanks.

**Comment by nbcsm** [comment] 2019-03-27 13:05
will close it, please reopen if there is any issue.

**Closed by nbcsm** 2019-03-27 13:05 UTC
Labels: enhancement
